[phases.setup]
aptPkgs = ["ffmpeg", "libxcb1", "libxext6", "libxrender1", "libgl1"]

[phases.install]
cmds = ["pip install --upgrade pip", "pip install -r requirements.txt"]

[start]
cmd = "python bot.py"
