[phases.setup]
aptPkgs = ["ffmpeg", "libxcb1", "libx11-6", "libxext6", "libxrender1", "libgl1", "libglib2.0-0"]

[phases.install]
cmds = ["pip install --upgrade pip", "pip install -r requirements.txt"]

[start]
cmd = "python bot.py"
